/*
  Auto-generated by Spline
*/

import { useThree } from '@react-three/fiber'
import useSpline from '@splinetool/r3f-spline'
import { PerspectiveCamera } from '@react-three/drei'
import Game from './Game'

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/kOg1I8r23bnFnDbb/scene.splinecode')
  const state = useThree()
  let value = 1
  const action = (e) =>{
    console.log(state.scene)
    console.log(state.scene.getObjectByName(`Path${value}`))
    console.log(value)
    e.object.position.x =state.scene.getObjectByName(`Path${value}`).position.x
    e.object.position.z =state.scene.getObjectByName(`Path${value}`).position.z
    console.log(value)
    value = value +1
    console.log(value)
  }
  const diceRoll = (e) =>{
    console.log(e)
    rollDice()
  }
  // function returns a dice randon dice value
  function rollDice() {
    const diceOption = [1, 2, 3, 4, 5, 6]
    let dice = diceOption[Math.floor(Math.random() * 6)]
    return dice
  }

  
   return (
    <>
      <color attach="background" args={['#fef3e2']} />
      <group {...props} dispose={null}>
        <mesh
          name="yellow4"
          geometry={nodes.yellow4.geometry}
          material={materials['yellow4 Material']}
          castShadow
          receiveShadow
          position={[-861.41, 132.35, 1386.42]}
          scale={[1.68, 2.5, 0.99]}
          onClick={action}
        />
        <mesh
          name="yellow3"
          geometry={nodes.yellow3.geometry}
          material={materials['yellow3 Material']}
          castShadow
          receiveShadow
          position={[-1229.15, 132.35, 1386.42]}
          scale={[1.68, 2.5, 0.99]}
          onClick={action}
        />
        <mesh
          name="yellow2"
          geometry={nodes.yellow2.geometry}
          material={materials['yellow2 Material']}
          castShadow
          receiveShadow
          position={[-1229.15, 132.35, 772.39]}
          scale={[1.68, 2.5, 0.99]}
          onClick={action}
        />
        <mesh
          name="yellow1"
          geometry={nodes.yellow1.geometry}
          material={materials['yellow1 Material']}
          castShadow
          receiveShadow
          position={[-861.41, 132.35, 772.39]}
          scale={[1.68, 2.5, 0.99]}
          onClick={action}
        />
        <mesh
          name="blue4"
          geometry={nodes.blue4.geometry}
          material={materials['blue4 Material']}
          castShadow
          receiveShadow
          position={[-861.41, 132.35, -209.66]}
          scale={[1.68, 2.5, 0.99]}
          onClick={action}
        />
        <mesh
          name="blue 3"
          geometry={nodes['blue 3'].geometry}
          material={materials['blue 3 Material']}
          castShadow
          receiveShadow
          position={[-1229.15, 132.35, -209.66]}
          scale={[1.68, 2.5, 0.99]}
          onClick={action}
        />
        <mesh
          name="blue2"
          geometry={nodes.blue2.geometry}
          material={materials['blue2 Material']}
          castShadow
          receiveShadow
          position={[-1229.15, 132.35, -823.69]}
          scale={[1.68, 2.5, 0.99]}
          onClick={action}
        />
        <mesh
          name="blue1"
          geometry={nodes.blue1.geometry}
          material={materials['blue1 Material']}
          castShadow
          receiveShadow
          position={[-861.41, 132.35, -823.69]}
          scale={[1.68, 2.5, 0.99]}
          onClick={action}
        />
        <mesh
          name="green4"
          geometry={nodes.green4.geometry}
          material={materials['green4 Material']}
          castShadow
          receiveShadow
          position={[615.74, 132.35, -209.66]}
          scale={[1.68, 2.5, 0.99]}
          onClick={action}
        />
        <mesh
          name="green3"
          geometry={nodes.green3.geometry}
          material={materials['green3 Material']}
          castShadow
          receiveShadow
          position={[248, 132.35, -209.66]}
          scale={[1.68, 2.5, 0.99]}
          onClick={action}
        />
        <mesh
          name="green2"
          geometry={nodes.green2.geometry}
          material={materials['green2 Material']}
          castShadow
          receiveShadow
          position={[248, 132.35, -823.69]}
          scale={[1.68, 2.5, 0.99]}
          onClick={action}
        />
        <mesh
          name="green1"
          geometry={nodes.green1.geometry}
          material={materials['green1 Material']}
          castShadow
          receiveShadow
          position={[615.74, 132.35, -823.69]}
          scale={[1.68, 2.5, 0.99]}
          onClick={action}
        />
        <mesh
          name="Red1"
          geometry={nodes.Red1.geometry}
          material={materials['Red1 Material']}
          castShadow
          receiveShadow
          position={[615.74, 132.35, 1408.09]}
          scale={[1.68, 2.5, 0.99]}
          onClick={action}
        />
        <mesh
          name="Red2"
          geometry={nodes.Red2.geometry}
          material={materials['Red2 Material']}
          castShadow
          receiveShadow
          position={[248, 132.35, 1408.09]}
          scale={[1.68, 2.5, 0.99]}
          onClick={action}
        />
        <mesh
          name="Red3"
          geometry={nodes.Red3.geometry}
          material={materials['Red3 Material']}
          castShadow
          receiveShadow
          position={[248, 132.35, 794.05]}
          scale={[1.68, 2.5, 0.99]}
          onClick={action}
        />
        <mesh
          name="Red4"
          geometry={nodes.Red4.geometry}
          material={materials['Red4 Material']}
          castShadow
          receiveShadow
          position={[615.74, 132.35, 794.05]}
          scale={[1.68, 2.5, 0.99]}
          onClick={action}
        />
        <mesh
          name="Dice"
          geometry={nodes.Dice.geometry}
          material={materials['Dice Material']}
          castShadow
          receiveShadow
          position={[1841.1, 297.28, 1016.15]}
          rotation={[-Math.PI, 1.54, -Math.PI]}
          scale={1}
        />
        <mesh
          name="Shape"
          geometry={nodes.Shape.geometry}
          material={materials['Shape Material']}
          castShadow
          receiveShadow
          position={[1875.4, 1230.52, 138.2]}
          rotation={[-1.97, -0.1, -2.91]}
          scale={1}
        />
        <mesh
          name="Cube 21"
          geometry={nodes['Cube 21'].geometry}
          material={materials['Cube 21 Material']}
          castShadow
          receiveShadow
          position={[-1169.47, -58.76, 297.5]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Cube 20"
          geometry={nodes['Cube 20'].geometry}
          material={materials['Cube 20 Material']}
          castShadow
          receiveShadow
          position={[-854.43, -55.69, 298.82]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Cube 201"
          geometry={nodes['Cube 201'].geometry}
          material={materials['Cube 201 Material']}
          castShadow
          receiveShadow
          position={[-696.52, -55.69, 299.26]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path12"
          geometry={nodes.Path12.geometry}
          material={materials['Path12 Material']}
          castShadow
          receiveShadow
          position={[-1488.41, -58.76, 297.06]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Cube 202"
          geometry={nodes['Cube 202'].geometry}
          material={materials['Cube 202 Material']}
          castShadow
          receiveShadow
          position={[-1330.5, -58.76, 297.5]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Cube 203"
          geometry={nodes['Cube 203'].geometry}
          material={materials['Cube 203 Material']}
          castShadow
          receiveShadow
          position={[-1012.9, -55.69, 298.38]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path17"
          geometry={nodes.Path17.geometry}
          material={materials['Path17 Material']}
          castShadow
          receiveShadow
          position={[-853.87, -55.69, 96.81]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path18"
          geometry={nodes.Path18.geometry}
          material={materials['Path18 Material']}
          castShadow
          receiveShadow
          position={[-695.95, -55.69, 97.25]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path13"
          geometry={nodes.Path13.geometry}
          material={materials['Path13 Material']}
          castShadow
          receiveShadow
          position={[-1487.85, -58.76, 95.05]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path14"
          geometry={nodes.Path14.geometry}
          material={materials['Path14 Material']}
          castShadow
          receiveShadow
          position={[-1329.94, -58.76, 95.49]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path15"
          geometry={nodes.Path15.geometry}
          material={materials['Path15 Material']}
          castShadow
          receiveShadow
          position={[-1170.25, -55.69, 95.93]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path16"
          geometry={nodes.Path16.geometry}
          material={materials['Path16 Material']}
          castShadow
          receiveShadow
          position={[-1012.34, -55.69, 96.37]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path7"
          geometry={nodes.Path7.geometry}
          material={materials['Path7 Material']}
          castShadow
          receiveShadow
          position={[-854.98, -58.76, 497.95]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path6"
          geometry={nodes.Path6.geometry}
          material={materials['Path6 Material']}
          castShadow
          receiveShadow
          position={[-697.07, -58.76, 498.39]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name=" Path11"
          geometry={nodes[' Path11'].geometry}
          material={materials[' Path11 Material']}
          castShadow
          receiveShadow
          position={[-1488.97, -58.76, 496.18]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path10"
          geometry={nodes.Path10.geometry}
          material={materials['Path10 Material']}
          castShadow
          receiveShadow
          position={[-1331.05, -58.76, 496.62]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path9"
          geometry={nodes.Path9.geometry}
          material={materials['Path9 Material']}
          castShadow
          receiveShadow
          position={[-1171.37, -58.76, 497.06]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path8"
          geometry={nodes.Path8.geometry}
          material={materials['Path8 Material']}
          castShadow
          receiveShadow
          position={[-1013.46, -58.76, 497.5]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Cube 19"
          geometry={nodes['Cube 19'].geometry}
          material={materials['Cube 19 Material']}
          castShadow
          receiveShadow
          position={[712.68, -55.69, 298.82]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path38"
          geometry={nodes.Path38.geometry}
          material={materials['Path38 Material']}
          castShadow
          receiveShadow
          position={[870.59, -55.69, 299.26]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Cube 191"
          geometry={nodes['Cube 191'].geometry}
          material={materials['Cube 191 Material']}
          castShadow
          receiveShadow
          position={[78.7, -58.76, 297.06]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Cube 192"
          geometry={nodes['Cube 192'].geometry}
          material={materials['Cube 192 Material']}
          castShadow
          receiveShadow
          position={[236.61, -58.76, 297.5]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Cube 193"
          geometry={nodes['Cube 193'].geometry}
          material={materials['Cube 193 Material']}
          castShadow
          receiveShadow
          position={[396.29, -55.69, 297.94]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Cube 194"
          geometry={nodes['Cube 194'].geometry}
          material={materials['Cube 194 Material']}
          castShadow
          receiveShadow
          position={[554.2, -55.69, 298.38]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path36"
          geometry={nodes.Path36.geometry}
          material={materials['Path36 Material']}
          castShadow
          receiveShadow
          position={[713.24, -55.69, 96.81]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path37"
          geometry={nodes.Path37.geometry}
          material={materials['Path37 Material']}
          castShadow
          receiveShadow
          position={[871.15, -55.69, 97.25]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path32"
          geometry={nodes.Path32.geometry}
          material={materials['Path32 Material']}
          castShadow
          receiveShadow
          position={[79.26, -58.76, 95.05]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path33"
          geometry={nodes.Path33.geometry}
          material={materials['Path33 Material']}
          castShadow
          receiveShadow
          position={[235.76, -60.42, 95.49]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path34"
          geometry={nodes.Path34.geometry}
          material={materials['Path34 Material']}
          castShadow
          receiveShadow
          position={[396.85, -55.69, 95.93]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path35"
          geometry={nodes.Path35.geometry}
          material={materials['Path35 Material']}
          castShadow
          receiveShadow
          position={[554.77, -55.69, 96.37]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path40"
          geometry={nodes.Path40.geometry}
          material={materials['Path40 Material']}
          castShadow
          receiveShadow
          position={[712.12, -58.76, 497.95]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path39"
          geometry={nodes.Path39.geometry}
          material={materials['Path39 Material']}
          castShadow
          receiveShadow
          position={[870.04, -58.76, 498.39]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path44"
          geometry={nodes.Path44.geometry}
          material={materials['Path44 Material']}
          castShadow
          receiveShadow
          position={[78.14, -58.76, 496.18]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path43"
          geometry={nodes.Path43.geometry}
          material={materials['Path43 Material']}
          castShadow
          receiveShadow
          position={[236.05, -58.76, 496.62]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path42"
          geometry={nodes.Path42.geometry}
          material={materials['Path42 Material']}
          castShadow
          receiveShadow
          position={[395.74, -58.76, 497.06]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path41"
          geometry={nodes.Path41.geometry}
          material={materials['Path41 Material']}
          castShadow
          receiveShadow
          position={[553.65, -58.76, 497.5]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Cube 18"
          geometry={nodes['Cube 18'].geometry}
          material={materials['Cube 18 Material']}
          castShadow
          receiveShadow
          position={[-305.79, -55.69, -248.43]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Cube 181"
          geometry={nodes['Cube 181'].geometry}
          material={materials['Cube 181 Material']}
          castShadow
          receiveShadow
          position={[-305.79, -55.69, -90.51]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path25"
          geometry={nodes.Path25.geometry}
          material={materials['Path25 Material']}
          castShadow
          receiveShadow
          position={[-305.79, -55.69, -882.41]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Cube 182"
          geometry={nodes['Cube 182'].geometry}
          material={materials['Cube 182 Material']}
          castShadow
          receiveShadow
          position={[-305.79, -55.69, -724.5]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Cube 183"
          geometry={nodes['Cube 183'].geometry}
          material={materials['Cube 183 Material']}
          castShadow
          receiveShadow
          position={[-305.79, -55.69, -564.81]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Cube 184"
          geometry={nodes['Cube 184'].geometry}
          material={materials['Cube 184 Material']}
          castShadow
          receiveShadow
          position={[-305.79, -55.69, -406.9]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path30"
          geometry={nodes.Path30.geometry}
          material={materials['Path30 Material']}
          castShadow
          receiveShadow
          position={[-103.78, -55.69, -248.43]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path31"
          geometry={nodes.Path31.geometry}
          material={materials['Path31 Material']}
          castShadow
          receiveShadow
          position={[-103.78, -55.69, -90.51]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path26"
          geometry={nodes.Path26.geometry}
          material={materials['Path26 Material']}
          castShadow
          receiveShadow
          position={[-103.78, -55.69, -882.41]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path27"
          geometry={nodes.Path27.geometry}
          material={materials['Path27 Material']}
          castShadow
          receiveShadow
          position={[-103.78, -55.69, -724.5]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path28"
          geometry={nodes.Path28.geometry}
          material={materials['Path28 Material']}
          castShadow
          receiveShadow
          position={[-103.78, -55.69, -564.81]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path29"
          geometry={nodes.Path29.geometry}
          material={materials['Path29 Material']}
          castShadow
          receiveShadow
          position={[-103.78, -55.69, -406.9]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path20"
          geometry={nodes.Path20.geometry}
          material={materials['Path20 Material']}
          castShadow
          receiveShadow
          position={[-504.91, -55.69, -248.43]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path19"
          geometry={nodes.Path19.geometry}
          material={materials['Path19 Material']}
          castShadow
          receiveShadow
          position={[-504.91, -55.69, -90.51]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path24"
          geometry={nodes.Path24.geometry}
          material={materials['Path24 Material']}
          castShadow
          receiveShadow
          position={[-504.91, -55.69, -882.41]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path23"
          geometry={nodes.Path23.geometry}
          material={materials['Path23 Material']}
          castShadow
          receiveShadow
          position={[-504.91, -55.69, -724.5]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path22"
          geometry={nodes.Path22.geometry}
          material={materials['Path22 Material']}
          castShadow
          receiveShadow
          position={[-504.91, -55.69, -564.81]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path21"
          geometry={nodes.Path21.geometry}
          material={materials['Path21 Material']}
          castShadow
          receiveShadow
          position={[-504.91, -55.69, -406.9]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Cube 15"
          geometry={nodes['Cube 15'].geometry}
          material={materials['Cube 15 Material']}
          castShadow
          receiveShadow
          position={[-305.79, -55.69, 1318.15]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path51"
          geometry={nodes.Path51.geometry}
          material={materials['Path51 Material']}
          castShadow
          receiveShadow
          position={[-305.79, -55.69, 1476.06]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Cube 151"
          geometry={nodes['Cube 151'].geometry}
          material={materials['Cube 151 Material']}
          castShadow
          receiveShadow
          position={[-305.79, -55.69, 684.16]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Cube 152"
          geometry={nodes['Cube 152'].geometry}
          material={materials['Cube 152 Material']}
          castShadow
          receiveShadow
          position={[-305.79, -55.69, 842.07]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Cube 153"
          geometry={nodes['Cube 153'].geometry}
          material={materials['Cube 153 Material']}
          castShadow
          receiveShadow
          position={[-305.79, -55.69, 1001.76]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Cube 154"
          geometry={nodes['Cube 154'].geometry}
          material={materials['Cube 154 Material']}
          castShadow
          receiveShadow
          position={[-305.79, -55.69, 1159.67]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path49"
          geometry={nodes.Path49.geometry}
          material={materials['Path49 Material']}
          castShadow
          receiveShadow
          position={[-103.78, -55.69, 1318.15]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path50"
          geometry={nodes.Path50.geometry}
          material={materials['Path50 Material']}
          castShadow
          receiveShadow
          position={[-103.78, -55.69, 1476.06]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path45"
          geometry={nodes.Path45.geometry}
          material={materials['Path45 Material']}
          castShadow
          receiveShadow
          position={[-103.78, -55.69, 684.16]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path46"
          geometry={nodes.Path46.geometry}
          material={materials['Path46 Material']}
          castShadow
          receiveShadow
          position={[-103.78, -55.69, 842.07]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path47"
          geometry={nodes.Path47.geometry}
          material={materials['Path47 Material']}
          castShadow
          receiveShadow
          position={[-103.78, -55.69, 1001.76]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path48"
          geometry={nodes.Path48.geometry}
          material={materials['Path48 Material']}
          castShadow
          receiveShadow
          position={[-103.78, -55.69, 1159.67]}
          rotation={[0, 0, 0]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path1"
          geometry={nodes.Path1.geometry}
          material={materials['Path1 Material']}
          castShadow
          receiveShadow
          position={[-504.91, -55.69, 1318.15]}
          rotation={[0, 0, 0]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path52"
          geometry={nodes.Path52.geometry}
          material={materials['Path52 Material']}
          castShadow
          receiveShadow
          position={[-504.91, -55.69, 1476.06]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path5"
          geometry={nodes.Path5.geometry}
          material={materials['Path5 Material']}
          castShadow
          receiveShadow
          position={[-504.91, -55.69, 684.16]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path4"
          geometry={nodes.Path4.geometry}
          material={materials['Path4 Material']}
          castShadow
          receiveShadow
          position={[-504.91, -55.69, 842.07]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path3"
          geometry={nodes.Path3.geometry}
          material={materials['Path3 Material']}
          castShadow
          receiveShadow
          position={[-504.91, -55.69, 1001.76]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Path2"
          geometry={nodes.Path2.geometry}
          material={materials['Path2 Material']}
          castShadow
          receiveShadow
          position={[-504.91, -55.69, 1159.67]}
          scale={[1.41, 0.83, 0.95]}
        />
        <mesh
          name="Cube 9"
          geometry={nodes['Cube 9'].geometry}
          material={materials['Cube 9 Material']}
          castShadow
          receiveShadow
          position={[-304.38, -48, 299.42]}
        />
        <directionalLight
          name="Directonal Light"
          castShadow
          intensity={0.75}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={-10000}
          shadow-camera-far={100000}
          shadow-camera-left={-1150}
          shadow-camera-right={1150}
          shadow-camera-top={1150}
          shadow-camera-bottom={-1150}
          position={[268.6, 664.71, -274.27]}
          rotation={[0, -0.04, 0]}
          scale={1}
        />
        <mesh
          name="Cube"
          geometry={nodes.Cube.geometry}
          material={materials['Cube Material']}
          castShadow
          receiveShadow
          position={[-1083.73, -48, 1076.08]}
        />
        <mesh
          name="Cube 4"
          geometry={nodes['Cube 4'].geometry}
          material={materials['Cube 4 Material']}
          castShadow
          receiveShadow
          position={[479.08, -48, 1079.46]}
        />
        <mesh
          name="Cube 5"
          geometry={nodes['Cube 5'].geometry}
          material={materials['Cube 5 Material']}
          castShadow
          receiveShadow
          position={[-1079.82, -48, -480.45]}
        />
        <mesh
          name="Cube 51"
          geometry={nodes['Cube 51'].geometry}
          material={materials['Cube 51 Material']}
          castShadow
          receiveShadow
          position={[477.61, -48, -481.32]}
        />
        <PerspectiveCamera
          name="1"
          makeDefault={true}
          far={100000}
          near={5}
          fov={45}
          position={[-3202.54, 7170.96, 526.17]}
          rotation={[-1.69, -0.4, -1.86]}
          scale={1}
        />
      </group>
    </>
  )
}
